### ISSUE TITLE
3.1 - bontà di classificazione

### ISSUE THREAD

**Issue by EnricoGiampieri** [Mat092/Tesi_latex#10]
Quando descrivi i risultati della classificazione nei dataset, metti un riferimento alle figure a seguito nel capitolo, altrimenti sembra che tu non abbia mai associato un numero alla bontà di classificazione.

**Comment by EnricoGiampieri** [comment]
nella sezione 3.2, metti la frase `l'obiettivo non è stato quello di trovare la ree più performante`.

Questa frase mi sembra poco chiara se non addirittura il contrario di quello che abbiamo fatto.

**Comment by EnricoGiampieri** [comment]
la log loss ha un limite **superiore**, non inferiore.

Inoltre se lo citi metterei anche una spiegazione nella parte di metodi che questo limite è pari a `-log(0.5)` quando le due classi sono bllanciate e il predittore ritorna 0.5 (incertezza totale) in tutti i casi. Inoltre non è un vero e proprio limite quando il limite *in media*, ma si possono ottenere risultati superiori in base alla combinzione di dati.

Non è al 100% preciso ma è meglio che citarlo senza spiegazioni.

**Comment by EnricoGiampieri** [comment]
a pagina 26 hai invertito, uno score più alto deve rappresentare una fitness più bassa, altrimenti staresti selezionando per reti che fanno più schifo possibile.

**Comment by Mat092** [comment]
> nella sezione 3.2, metti la frase `l'obiettivo non è stato quello di trovare la ree più performante`.
> 
> Questa frase mi sembra poco chiara se non addirittura il contrario di quello che abbiamo fatto.

Si in effetti non sono stato per niente chiaro, intendevo dire `più performante` in termini di calcolo/computazionali. Specifico

**Comment by Mat092** [comment]
> la log loss ha un limite **superiore**, non inferiore.

Qui per limite inferiore intendevo dire che non esiste un vero e proprio "zero" , o rete perfetta, per la log loss e i risultati che in seguto consideriamo a fitness nullo in realtà sarebbero dei 3 * 10^-5 (o cose cosi), quindi, in teoria, è possibile che l'algoritmo trovi un 2 * 10 ^-5, che è migliore, ma in modo praticamente irrilevante, la rete raggiunge comunque lo scopo di separare ogni punto correttamente.

Scrivo questo come spiegazione.
