### ISSUE TITLE
aggiungere materiale all'inizio dell'introduzione

### ISSUE THREAD

**Issue by EnricoGiampieri** [Mat092/Tesi_latex#3]
L'introduzione ha bisogno di essere arricchita un po'.

Ti serve per far capire bene il contesto a chi sta leggendo.
Di solito si fa una specie di testo riassuntivo dell'outline della tesi, con un paragrafo che spiega il contenuto dei vari capitoli.

Ci andrebbe anche un paragrafo che apra sul perchè questa ricerca è interessante: nel tuo caso stiamo cercando di caratterizzare (anche se su dataset artificiali) come e quanto la struttura e la rumorosità dei dati influenzino la complessità della rete.
Per fare questo, e per cercare la miglior rete possibile senza esplorare di forza tutte le possibili combinazioni, abbiamo usato un algoritmo genetico.

Questa parte ti farà comodo per quando dovrai fare la domanda di laurea, in cui credo che ti chiedano anche un abstract della tesi, e nel caso questi paragrafi ti faranno comodo.

**Comment by Mat092** [comment]
@EnricoGiampieri 
Salve, riguardo al secondo paragrafo: questo sarebbe l'abstract giusto? 
dovrei metterlo ad inizio tesi, prima dell'indice? Oppure iniziare il capitolo "introduzione" con quello e poi inserirlo solo dove richiesto durante il caricamento?

**Comment by EnricoGiampieri** [comment]
direi che può andare bene.

In caso ti rimanesse un po' di tempo ed energia alla fine, questa è la parte in cui vale la pena limare meglio i contenuti perchè è anche quella che probabilmente (insieme alle conclusioni) leggeranno.
